// ln200 header file for cb98

#define YES 1
#define NO 0

#define HEADING_VALID 1
#define HEADING_INVALID 0


// boresight entries
// X_AXIS is rotation about X, or roll
// Y_AXIS is pitch
// negative change in boresight causes positive change in readout
//#define X_AXIS -0.277 
#define X_AXIS +0.4  //   // roll jtm 9/3/03
//#define Y_AXIS +0.126 
#define Y_AXIS +0.1      // pitch jtm 9/3/03
#define Z_AXIS 0.0

#define LATITUDE 38.9970
//#define BEARING 123.0
//#define BEARING1 127.0
//#define BEARING2 307.0
